# Generated by Django 4.0.1 on 2022-03-27 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDeviceInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('request_Id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemDeviceInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('request_Id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WifiDeviceInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('request_Id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
