# Generated by Django 4.0.1 on 2022-04-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_networkdeviceinfo_alpn_networkdeviceinfo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdeviceinfo',
            name='flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkdeviceinfo',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkdeviceinfo',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkdeviceinfo',
            name='ver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeviceinfo',
            name='flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeviceinfo',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeviceinfo',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeviceinfo',
            name='ver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifideviceinfo',
            name='flag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifideviceinfo',
            name='timestamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifideviceinfo',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifideviceinfo',
            name='ver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
