# Generated by Django 4.0.4 on 2022-05-06 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_brokerdetails_device_remove_networkdeviceinfo_alpn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=1883, max_length=5)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('server_topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerDeviceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_topic', models.CharField(max_length=255)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.brokerdetail')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='broker.device')),
            ],
        ),
        migrations.DeleteModel(
            name='BrokerDetails',
        ),
    ]
