# Generated by Django 4.0.4 on 2022-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_brokerdetail_brokerdevicetopic_delete_brokerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='networkdeviceinfo',
            name='macaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkdeviceinfo',
            name='serial_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeviceinfo',
            name='macaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeviceinfo',
            name='serial_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifideviceinfo',
            name='macaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifideviceinfo',
            name='serial_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brokerdetail',
            name='port',
            field=models.IntegerField(default=1883),
        ),
        migrations.AlterField(
            model_name='networkdeviceinfo',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemdeviceinfo',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wifideviceinfo',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
