# Generated by Django 4.0.4 on 2022-05-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_unregistereddevice_networkdeviceinfo_macaddr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdeviceinfo',
            name='macaddr',
        ),
        migrations.RemoveField(
            model_name='networkdeviceinfo',
            name='serial_num',
        ),
        migrations.RemoveField(
            model_name='systemdeviceinfo',
            name='macaddr',
        ),
        migrations.RemoveField(
            model_name='systemdeviceinfo',
            name='serial_num',
        ),
        migrations.RemoveField(
            model_name='wifideviceinfo',
            name='macaddr',
        ),
        migrations.RemoveField(
            model_name='wifideviceinfo',
            name='serial_num',
        ),
    ]
