# Generated by Django 4.0.4 on 2022-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_remove_networkdeviceinfo_macaddr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdeviceinfo',
            name='macaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemdeviceinfo',
            name='macaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wifideviceinfo',
            name='macaddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
